.\" Copyright (c) 1999-2005 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" 
.\" 
.TH "perl-cleaner" "1" "1" "Michael Cummings" "Gentoo UserLand Tools"
.SH "NAME"
perl\-cleaner <OPTIONS> (ask)
.SH "DESCRIPTION"
Clean up old perl installations, attempting to emerge \-\-oneshot packages left over from a perl upgrade, as well as any packages that linked against the old version of libperl.so.

.SH "USAGE"
.TP 7
\fBmodules\fR 
Rebuild perl modules installed under previous versions of perl
.TP 7
\fBallmodules\fR 
Rebuild perl modules installed under any version of perl, even current
.TP 7
\fBlibperl\fR
Rebuild anything linked against libperl.
.TP 7
\fBph\-clean\fR
Clean out old ph files from previous versions of perl, removing empty directories as possible
.TP 7
\fBphupdate\fR
Update existing ph files, useful after an upgrade to the system, such as new kernel headers, security headers, etc.
.TP 7
\fBphall\fR
Clean out old ph files and directories, then run update existing ph files
.TP 7
\fBall\fR
Rebuild modules, libperl linkages, clean up ph files, and rebuild/build ph files
.TP 7
\fBreallyall\fR
Rebuild all modules for any version of perl, libperl linkages, clean up ph files, and rebuild/build ph files. This is particular useful on severly broken systems, and boxes where you have chosen to change from a threaded to a non-threaded (or vice versa) perl, but it is still the same version release of perl (ie, 5.8.5, 5.8.6).
.br 
.TP 7
\fBask\fR
Pass emerge the "\-\-ask" option
.SH "SEE ALSO"
\fIperl\fR, \fIemerge\fR, \fIrevdep\-rebuild\fR
.SH "BUGS"
Please post any bugs to \fIhttp://bugs.gentoo.org\fR or \fIhttps://bugs.gentoo.org\fR assigned to perl@gentoo.org
.SH "AUTHORS"
Michael Cummings (mcummings@gentoo.org)

Mr.B ones [contributor] (mr_bones_@gentoo.org)

swtaylor [contributor] (swtaylor@gentoo.org)
